var dateModule = require('./date');

/**
 * CS Mezinárodní dny
 * https://www.kurzy.cz/kalendar/mezinarodni-dny/2021/
 */
const internationalDays = {
    1: {
        1: ['Světový den míru'],
        4: ['Světový den Braillova písma'],
        5: [''],
        6: [''],
        7: [''],
        8: [''],
        9: [''],
        10: [''],
        11: [''],
        12: [''],
        13: [''],
        14: [''],
        15: [''],
        16: [''],
        17: [''],
        18: [''],
        19: [''],
        20: [''],
        21: [''],
        22: [''],
        23: [''],
        24: [''],
        25: [''],
        26: ['Mezinárodní den celníků'],
        27: ['Mezinárodní den památky obětí holocaustu'],
        28: ['Den ochrany osobních údajů'],
        29: ['Den dětí ulice'],
        30: [''],
        31: ['']
    },
    2: {
        1: [''],
        2: ['Světový den mokřadů'],
        3: [''],
        4: ['Světový den boje proti rakovině'],
        5: [''],
        6: ['Mezinárodní den nulové tolerance ženské obřízce'],
        7: [''],
        8: [''],
        9: [''],
        10: [''],
        11: ['Světový den nemocných', 'Mezinárodní den žen a dívek ve vědě'],
        12: ['Den červené ruky', 'Darwinův den'],
        13: ['Světový den rádia'],
        14: [''],
        15: ['Mezinárodní Visegrádský Den'],
        16: [''],
        17: [''],
        18: [''],
        19: [''],
        20: ['Světový den sociální spravedlnosti'],
        21: ['Mezinárodní den mateřského jazyka', 'Mezinárodní den průvodců cestovního ruchu', 'Mezinárodní den boje proti kolonialismu'],
        22: ['Evropský den obětí zločinu', 'Den sesterství'],
        23: [''],
        24: [''],
        25: [''],
        26: [''],
        27: [''],
        28: [''],
        29: [''],
        30: [''],
        31: ['']
    },
    3: {
        1: ['Mezinárodního dne civilní ochrany', 'Den nulové diskriminace'],
        2: [''],
        3: ['Světový den divoké přírody'],
        4: [''],
        5: [''],
        6: [''],
        7: [''],
        8: [''],
        9: [''],
        10: [''],
        11: ['Evropský den mozku', 'Evropský den památky obětem terorismu'],
        12: [''],
        13: [''],
        14: ['Den pí', 'Mezinárodní den akcí pro řeky a proti přehradám'],
        15: ['Mezinárodní den proti policejní brutalitě'],
        16: [''],
        17: [''],
        18: [''],
        19: [''],
        20: ['Světový den štěstí', 'Světový den frankofonie', 'Světový den divadla pro děti a mládež', 'Světový den vrabců'],
        21: ['Světový den Downova syndromu', 'Světový den poezie', 'Mezinárodní den za odstranění rasové diskriminace', 'Mezinárodní den loutkového divadla', 'Mezinárodní den lesů', 'Nourúz'],
        22: ['Světový den vody', 'Světový den mimů'],
        23: ['Světový den meteorologie'],
        24: ['Světový den boje proti tuberkulóze', 'Mezinárodní den za právo na pravdu o hrubém porušování lidských práv a na důstojnost obětí'],
        25: [''],
        26: ['Světový den boje proti epilepsii'],
        27: ['Světový den divadla'],
        28: [''],
        29: [''],
        30: [''],
        31: ['']
    },
    4: {
        1: ['Mezinárodní den ptactva'],
        2: ['Mezinárodní den dětské knihy', 'Světový den zvýšení povědomí o autismu'],
        3: [''],
        4: ['Mezinárodní den proti nášlapným minám'],
        5: [''],
        6: ['Mezinárodní den sportu za rozvoj a mír'],
        7: [''],
        8: ['Mezinárodní den Romů'],
        9: [''],
        10: [''],
        11: ['Mezinárodní den solidarity osvobození politických vězňů', 'Světový den Parkinsonovy choroby'],
        12: ['Mezinárodní den kosmonautiky'],
        13: [''],
        14: ['Světový den monitoringu diabetiků'],
        15: [''],
        16: ['Světový den hlasu'],
        17: ['Světový den hemofilie'],
        18: ['Mezinárodní den památek a sídel', 'Mezinárodní den radioamatérů'],
        19: ['Světový den investičních fondů'],
        20: ['Světový den marihuany'],
        21: [''],
        22: ['Mezinárodní den Země'],
        23: ['Světový den knihy a autorského práva', 'Den anglického jazyka'],
        24: ['Mezinárodní den skautů a skautek', 'Světový den laboratorních zvířat'],
        25: ['Světový den boje proti malárii'],
        26: ['Světový den duševního vlastnictví'],
        27: ['Světový den grafiky'],
        28: ['Světový den bezpečnosti a ochrany zdraví při práci'],
        29: ['Mezinárodní den tance', 'Mezinárodní den obětí chemických válek', 'Mezinárodní den imunologie'],
        30: ['Mezinárodní den jazzu'],
        31: ['']
    },
    5: {
        1: [''],
        2: [''],
        3: ['Mezinárodní den svobody tisku'],
        4: ['Mezinárodní den hasičů', 'Den Star Wars'],
        5: ['Mezinárodní den porodních asistentek', 'Mezinárodní den hygieny rukou', 'Evropský den pro rovnoprávnost osob se zdravotním postižením'],
        6: ['Mezinárodní den proti dietám'],
        7: [''],
        8: ['Vzpomínkový den na ty, kdo ztratili svůj život během druhé světové války', 'Světový den Červeného kříže'],
        9: ['Den Evropy', 'Den matek'],
        10: [''],
        11: [''],
        12: [''],
        13: ['Mezinárodní den Falun Dafa', 'Světový den koktejlů'],
        14: [''],
        15: ['Den rodiny', 'Světový den proti mozkové mrtvici', 'Mezinárodní den odpůrců vojenské služby'],
        16: [''],
        17: ['Světový den informační společnosti', 'Mezinárodní den proti homofobii', 'Světový den hypertenze'],
        18: ['Mezinárodní den muzeí'],
        19: [''],
        20: [''],
        21: ['Světový den kulturní rozmanitosti'],
        22: ['Mezinárodní den biologické rozmanitosti'],
        23: ['Světový den želv'],
        24: ['Evropský den parků'],
        25: ['Geek Pride Day', 'Den Afriky', 'Mezinárodní den ztracených dětí', 'Ručníkový den'],
        26: [''],
        27: [''],
        28: ['Světový den her'],
        29: ['Mezinárodní den příslušníků mírových operací OSN'],
        30: [''],
        31: ['Světový den bez tabáku']
    },
    6: {
        1: ['Mezinárodní den dětí', 'Světový den rodičů', 'Světový den mléka'],
        2: ['Mezinárodní den prostitutek'],
        3: ['Evropský den jízdních kol'],
        4: ['Mezinárodní den dětí, které se staly obětí agrese'],
        5: ['Světový den životního prostředí'],
        6: [''],
        7: [''],
        8: ['Světový den oceánů', 'Světový den boje proti nádorům mozku'],
        9: ['Mezinárodní den archivů'],
        10: [''],
        11: [''],
        12: ['Světový den proti dětské práci'],
        13: [''],
        14: ['Světový den dárců krve'],
        15: ['Světový den proti násilí na seniorech', 'Světový den větru'],
        16: ['Den afrického dítěte'],
        17: ['Mezinárodní den proti rozšiřování pouští a sucha'],
        18: ['Autistický den hrdosti'],
        19: [''],
        20: ['Světový den uprchlíků', 'Den otců'],
        21: [''],
        22: ['Mezinárodní den bez kalhotek'],
        23: ['OSN pro den veřejné služby', 'Mezinárodní den vdov'],
        24: [''],
        25: ['Den námořníků'],
        26: [''],
        27: ['Světový den rybářství'],
        28: [''],
        29: [''],
        30: [''],
        31: ['']
    },
    7: {
        1: [''],
        2: ['Světový den UFO', 'Mezinárodní den proti zapomínání'],
        3: [''],
        4: [''],
        5: [''],
        6: ['Světový den polibku'],
        7: [''],
        8: [''],
        9: [''],
        10: [''],
        11: ['Světový den populace'],
        12: [''],
        13: [''],
        14: [''],
        15: [''],
        16: [''],
        17: [''],
        18: ['Mezinárodní den Nelsona Mandely'],
        19: [''],
        20: ['Mezinárodní den šachu'],
        21: [''],
        22: [''],
        23: [''],
        24: [''],
        25: [''],
        26: [''],
        27: [''],
        28: ['Světový den boje proti žloutence'],
        29: ['Mezinárodní den tygrů'],
        30: ['Mezinárodní den přátelství'],
        31: ['']
    },
    8: {
        1: [''],
        2: ['Den suchého zipu'],
        3: [''],
        4: [''],
        5: [''],
        6: ['Světový den boje za zákaz jaderných zbraní', 'Mezinárodní den boje lékařů za mír'],
        7: [''],
        8: [''],
        9: ['Mezinárodní den původního obyvatelstva'],
        10: [''],
        11: [''],
        12: ['Mezinárodní den mládeže'],
        13: ['Den leváků'],
        14: [''],
        15: ['Mezinárodní den energy drinků', 'Nanebevzetí Panny Marie'],
        16: ['Mezinárodní den rumu'],
        17: [''],
        18: [''],
        19: ['Světový den humanitárních pracovníků'],
        20: [''],
        21: [''],
        22: [''],
        23: ['Mezinárodní den památky obětí obchodu s otroky', 'Evropský den památky obětí stalinismu a nacismu'],
        24: [''],
        25: [''],
        26: [''],
        27: [''],
        28: [''],
        29: ['Mezinárodní den proti jaderným zkouškám'],
        30: ['Mezinárodní den obětí násilného zmizení'],
        31: ['']
    },
    9: {
        1: [''],
        2: [''],
        3: [''],
        4: [''],
        5: ['Mezinárodní den charity'],
        6: [''],
        7: [''],
        8: ['Mezinárodní den gramotnosti'],
        9: ['Evropský den recyklace baterií'],
        10: ['Světový den prevence sebevražd'],
        11: [''],
        12: ['Mezinárodní den OSN spolupráce jih-jih'],
        13: ['Mezinárodní den čokolády'],
        14: ['Evropský den židovské kultury'],
        15: [''],
        16: ['Mezinárodní den ochrany ozónové vrstvy', 'Den církevního školství'],
        17: [''],
        18: [''],
        19: [''],
        20: [''],
        21: ['Mezinárodní den míru', 'Mezinárodní den Alzheimerovy choroby'],
        22: [''],
        23: [''],
        24: [''],
        25: [''],
        26: ['Mezinárodní den antikoncepce'],
        27: ['Světový den cestovního ruchu'],
        28: ['Světový den boje proti vzteklině'],
        29: ['Světový den srdce'],
        30: ['Mezinárodní den překladatelů'],
        31: ['']
    },
    10: {
        1: [''],
        2: ['Světový den nenásilí', 'Světový den hospodářských zvířat'],
        3: [''],
        4: ['Mezinárodní den zvířat', 'Světový den lidských sídel'],
        5: ['Světový den učitelů'],
        6: [''],
        7: [''],
        8: ['Mezinárodní den boje proti popáleninám'],
        9: ['Světový den pošty'],
        10: [''],
        11: ['Mezinárodní den dívek'],
        12: ['Světový den boje proti artritidě', 'Mezinárodní den za omezení přírodních katastrof'],
        13: ['Mezinárodní den za omezení přírodních katastrof'],
        14: ['Světový den standardů'],
        15: [''],
        16: [''],
        17: ['Mezinárodní den za odstranění chudoby', 'Světový den úrazů'],
        18: [''],
        19: [''],
        20: ['Mezinárodní den kuchařů', 'Světový den statistiky', 'Světový den proti osteoporóze', 'Den stromů'],
        21: ['Den původních odrůd jablek'],
        22: ['Mezinárodní den balbutiků'],
        23: [''],
        24: ['Den Spojených národů', 'Světový den pro rozvoj informací'],
        25: [''],
        26: [''],
        27: ['Světový den audiovizuálního dědictví'],
        28: [''],
        29: [''],
        30: [''],
        31: ['Den UNICEF', 'Světový den spoření', 'Halloween']
    },
    11: {
        1: ['Všech svatých', 'Mezinárodní den veganství'],
        2: ['Dušičky'],
        3: ['Den bez pesticidů'],
        4: [''],
        5: [''],
        6: ['Mezinárodní den prevence ničení životního prostředí v průběhu válek a ozbrojených konfliktů'],
        7: [''],
        8: [''],
        9: [''],
        10: ['Světový den vědy pro mír a rozvoj'],
        11: ['Mezinárodní den válečných veteránů'],
        12: [''],
        13: ['Mezinárodní den nevidomých'],
        14: ['Světový den diabetiků', 'Den bez aut'],
        15: ['Den vězněných spisovatelů'],
        16: ['Mezinárodní den tolerance'],
        17: ['Mezinárodní den studentstva'],
        18: [''],
        19: ['Světový den prevence týrání a zneužívání dětí', 'Světový den toalet'],
        20: ['Den industrializace Afriky', 'Světový den dětí', 'Světový den chronické obstrukční plicní nemoci'],
        21: [''],
        22: [''],
        23: [''],
        24: [''],
        25: ['Mezinárodní den za odstranění násilí páchaného na ženách', 'Mezinárodní den bez nákupů'],
        26: [''],
        27: [''],
        28: [''],
        29: ['Mezinárodní den solidarity s lidem Palestiny'],
        30: [''],
        31: ['']
    },
    12: {
        1: ['Světový den boje proti AIDS'],
        2: ['Světový den počítačové gramotnosti', 'Mezinárodní den boje za vymýcení otroctví'],
        3: ['Mezinárodní den lidí s postižením'],
        4: [''],
        5: ['Mezinárodní den dobrovolníků'],
        6: [''],
        7: ['Mezinárodní den civilního letectví'],
        8: [''],
        9: ['Mezinárodní den proti korupci'],
        10: ['Den lidských práv'],
        11: ['Světový den dětství', 'Mezinárodní den hor'],
        12: [''],
        13: [''],
        14: [''],
        15: [''],
        16: [''],
        17: [''],
        18: ['Mezinárodní den migrantů'],
        19: [''],
        20: ['Mezinárodní den lidské solidarity'],
        21: [''],
        22: [''],
        23: [''],
        24: [''],
        25: [''],
        26: [''],
        27: [''],
        28: [''],
        29: ['Mezinárodní den biologické rozmanitosti'],
        30: [''],
        31: ['']
    }
} 

/**
 * 
 * 
 * @param {*} date 
 * @returns 
 */
module.exports.get = function (date) {
    const params = dateModule.getDayMonth(date);
    const month = params.month;
    const day = params.day;

    return internationalDays[month][day]
}