var dateModule = require('./date.js')

// ? TODO: Popis jmen

/**
 * CS Kalendář jmen
 * https://www.naplanuj-to.cz/kalendar-jmen
 */
const nameDays = {
    1: {
        1: ['Nový rok'],
        2: ['Karina', 'Vasil'],
        3: ['Radmila', 'Radomil'],
        4: ['Diana'],
        5: ['Dalimil'],
        6: ['Tři králové'],
        7: ['Vilma'],
        8: ['Čestmír'],
        9: ['Vladan', 'Valtr'],
        10: ['Břetislav'],
        11: ['Bohdana'],
        12: ['Pravoslav'],
        13: ['Edita'],
        14: ['Radovan'],
        15: ['Alice'],
        16: ['Ctirad'],
        17: ['Drahoslav'],
        18: ['Vladislav', 'Vladislava'],
        19: ['Doubravka'],
        20: ['Ilona', 'Sebastián'],
        21: ['Běla'],
        22: ['Slavomír', 'Slavomíra'],
        23: ['Zdeněk'],
        24: ['Milena'],
        25: ['Miloš'],
        26: ['Zora'],
        27: ['Ingrid'],
        28: ['Otýlie'],
        29: ['Zdislava'],
        30: ['Robin', 'Erna'],
        31: ['Marika']
    },
    2: {
        1: ['Hynek'],
        2: ['Nela', 'Hromnice'],
        3: ['Blažej'],
        4: ['Jarmila'],
        5: ['Dobromila'],
        6: ['Vanda'],
        7: ['Veronika', 'Verona'],
        8: ['Milada'],
        9: ['Apolena'],
        10: ['Mojmír'],
        11: ['Božena', 'Dezider'],
        12: ['Slavěna', 'Slávka'],
        13: ['Věnceslav', 'Věnceslava'],
        14: ['Valentýn', 'Valentýna'],
        15: ['Jiřina'],
        16: ['Ljuba'],
        17: ['Miloslava'],
        18: ['Gizela'],
        19: ['Patrik'],
        20: ['Oldřich'],
        21: ['Lenka', 'Eleonora'],
        22: ['Petr'],
        23: ['Svatopluk'],
        24: ['Matěj', 'Matyáš'],
        25: ['Liliana'],
        26: ['Dorota'],
        27: ['Alexandr'],
        28: ['Lumír'],
        29: ['Horymír'],
        30: [null],
        31: [null]
    },
    3: {
        1: ['Bedřich', 'Bedřiška'],
        2: ['Anežka'],
        3: ['Kamil'],
        4: ['Stela'],
        5: ['Kazimír'],
        6: ['Miroslav'],
        7: ['Tomáš'],
        8: ['Gabriela', 'Zoltán'],
        9: ['Františka'],
        10: ['Viktorie'],
        11: ['Anděla', 'Angelika'],
        12: ['Řehoř'],
        13: ['Růžena'],
        14: ['Rút', 'Matylda'],
        15: ['Ida'],
        16: ['Elena', 'Herbert'],
        17: ['Vlastimil', 'Vlastimila'],
        18: ['Eduard'],
        19: ['Josef', 'Josefa'],
        20: ['Světlana', 'Světla'],
        21: ['Radek'],
        22: ['Leona', 'Lea'],
        23: ['Ivona'],
        24: ['Gabriel'],
        25: ['Marián'],
        26: ['Emanuel'],
        27: ['Dita'],
        28: ['Soňa'],
        29: ['Taťána'],
        30: ['Arnošt', 'Ernest'],
        31: ['Kvido']
    },
    4: {
        1: ['Hugo'],
        2: ['Erika'],
        3: ['Richard'],
        4: ['Ivana'],
        5: ['Miroslava', 'Mirka'],
        6: ['Vendula', 'Venuše'],
        7: ['Heřman', 'Hermína'],
        8: ['Ema'],
        9: ['Dušan'],
        10: ['Darja'],
        11: ['Izabela'],
        12: ['Julius'],
        13: ['Aleš'],
        14: ['Vincenc'],
        15: ['Anastázie'],
        16: ['Irena'],
        17: ['Rudolf'],
        18: ['Valérie'],
        19: ['Rostislav', 'Rastislav'],
        20: ['Marcela'],
        21: ['Alexandra'],
        22: ['Evženie'],
        23: ['Vojtěch', 'Vojtěška'],
        24: ['Jiří'],
        25: ['Marek'],
        26: ['Oto'],
        27: ['Jaroslav'],
        28: ['Vlastislav'],
        29: ['Robert'],
        30: ['Blahoslav'],
        31: [null]
    },
    5: {
        1: ['Svátek práce'],
        2: ['Zikmund'],
        3: ['Alexej', 'Alex'],
        4: ['Květoslav'],
        5: ['Klaudie'],
        6: ['Radoslav', 'Radoslava'],
        7: ['Stanislav'],
        8: ['Den osvobození od fašismu'],
        9: ['Ctibor'],
        10: ['Blažena'],
        11: ['Svatava'],
        12: ['Pankrác'],
        13: ['Servác'],
        14: ['Bonifác'],
        15: ['Žofie', 'Sofie'],
        16: ['Přemysl'],
        17: ['Aneta'],
        18: ['Nataša'],
        19: ['Ivo'],
        20: ['Zbyšek'],
        21: ['Monika'],
        22: ['Emil'],
        23: ['Vladimír', 'Vladimíra'],
        24: ['Jana', 'Vanesa'],
        25: ['Viola'],
        26: ['Filip'],
        27: ['Valdemar'],
        28: ['Vilém', 'Viliam'],
        29: ['Maxmilián', 'Maxim'],
        30: ['Ferdinand'],
        31: ['Kamila']
    },
    6: {
        1: ['Laura'],
        2: ['Jarmil'],
        3: ['Tamara', 'Kevin'],
        4: ['Dalibor'],
        5: ['Dobroslav', 'Dobroslava'],
        6: ['Norbert'],
        7: ['Iveta', 'Slavoj'],
        8: ['Medard'],
        9: ['Stanislava'],
        10: ['Gita', 'Margita'],
        11: ['Bruno'],
        12: ['Antonie'],
        13: ['Antonín'],
        14: ['Roland', 'Herta'],
        15: ['Vít'],
        16: ['Zbyněk'],
        17: ['Adolf'],
        18: ['Milan', 'Milana'],
        19: ['Leoš', 'Leo'],
        20: ['Květa', 'Květuše'],
        21: ['Alois', 'Aloisie'],
        22: ['Pavla'],
        23: ['Zdeňka'],
        24: ['Jan'],
        25: ['Ivan'],
        26: ['Adriana', 'Adrian'],
        27: ['Ladislav', 'Ladislava'],
        28: ['Lubomír', 'Lubomíra'],
        29: ['Petr', 'Pavel'],
        30: ['Šárka'],
        31: [null]
    },
    7: {
        1: ['Jaroslava'],
        2: ['Patricie'],
        3: ['Radomír', 'Radomíra'],
        4: ['Prokop'],
        5: ['Cyril', 'Metoděj'],
        6: ['Den upálení mistra Jana Husa '],
        7: ['Bohuslava'],
        8: ['Nora'],
        9: ['Drahoslava', 'Drahuše'],
        10: ['Libuše', 'Amálie'],
        11: ['Olga', 'Helga'],
        12: ['Bořek'],
        13: ['Markéta'],
        14: ['Karolína'],
        15: ['Jindřich'],
        16: ['Luboš'],
        17: ['Martina'],
        18: ['Drahomíra', 'Drahomír'],
        19: ['Čeněk'],
        20: ['Eliáš', 'Ilja'],
        21: ['Vítězslav', 'Vítězslava'],
        22: ['Magdaléna', 'Magda'],
        23: ['Libor', 'Larisa'],
        24: ['Kristýna'],
        25: ['Jakub'],
        26: ['Anna', 'Anita'],
        27: ['Věroslav'],
        28: ['Viktor', 'Alina'],
        29: ['Marta'],
        30: ['Bořivoj'],
        31: ['Ignác']
    },
    8: {
        1: ['Oskar'],
        2: ['Gustav'],
        3: ['Miluše'],
        4: ['Dominik', 'Dominika'],
        5: ['Kristián'],
        6: ['Oldřiška'],
        7: ['Lada'],
        8: ['Soběslav'],
        9: ['Roman'],
        10: ['Vavřinec'],
        11: ['Zuzana'],
        12: ['Klára'],
        13: ['Alena'],
        14: ['Alan'],
        15: ['Hana'],
        16: ['Jáchym'],
        17: ['Petra'],
        18: ['Helena', 'Jelena'],
        19: ['Ludvík'],
        20: ['Bernard'],
        21: ['Johana'],
        22: ['Bohuslav'],
        23: ['Sandra'],
        24: ['Bartoloměj'],
        25: ['Radim'],
        26: ['Luděk', 'Luďka'],
        27: ['Otakar'],
        28: ['Augustýn'],
        29: ['Evelína'],
        30: ['Vladěna'],
        31: ['Pavlína']
    },
    9: {
        1: ['Linda', 'Samuel'],
        2: ['Adéla'],
        3: ['Bronislav', 'Bronislava'],
        4: ['Jindřiška', 'Rozálie'],
        5: ['Boris'],
        6: ['Boleslav'],
        7: ['Regína'],
        8: ['Mariana'],
        9: ['Daniela'],
        10: ['Irma'],
        11: ['Denis', 'Denisa'],
        12: ['Marie'],
        13: ['Lubor'],
        14: ['Radka'],
        15: ['Jolana'],
        16: ['Ludmila', 'Lidmila'],
        17: ['Naděžda', 'Naďa'],
        18: ['Kryštof'],
        19: ['Zita'],
        20: ['Oleg'],
        21: ['Matouš'],
        22: ['Darina'],
        23: ['Berta'],
        24: ['Jaromír', 'Jaromíra'],
        25: ['Zlata', 'Zlatuše'],
        26: ['Andrea'],
        27: ['Jonáš'],
        28: ['Václav', 'Václava', 'Den české státnosti'],
        29: ['Michal', 'Michael'],
        30: ['Jeroným'],
        31: [null]
    },
    10: {
        1: ['Igor'],
        2: ['Olívie', 'Oliver'],
        3: ['Bohumil'],
        4: ['František'],
        5: ['Eliška'],
        6: ['Hanuš'],
        7: ['Justýna'],
        8: ['Věra'],
        9: ['Štefan', 'Sára'],
        10: ['Marina'],
        11: ['Andrej'],
        12: ['Marcel'],
        13: ['Renáta', 'Koloman'],
        14: ['Agáta'],
        15: ['Tereza', 'Terezie'],
        16: ['Havel', 'Galina'],
        17: ['Hedvika', 'Heda'],
        18: ['Lukáš'],
        19: ['Michaela', 'Michala'],
        20: ['Vendelín'],
        21: ['Brigita'],
        22: ['Sabina'],
        23: ['Teodor'],
        24: ['Nina'],
        25: ['Beáta'],
        26: ['Erik'],
        27: ['Šarlota', 'Zoe'],
        28: ['Alfréd', 'Den vzniku samostatného československého státu'],
        29: ['Silvie', 'Sylva'],
        30: ['Tadeáš'],
        31: ['Štěpánka']
    },
    11: {
        1: ['Felix'],
        2: ['Tobiáš', 'Památka zesnulých'],
        3: ['Hubert'],
        4: ['Karel', 'Karla'],
        5: ['Miriam', 'Emerich'],
        6: ['Liběna'],
        7: ['Saskie', 'Andělín'],
        8: ['Bohumír', 'Bohumíra'],
        9: ['Bohdan'],
        10: ['Evžen'],
        11: ['Martin'],
        12: ['Benedikt'],
        13: ['Tibor'],
        14: ['Sáva'],
        15: ['Leopold'],
        16: ['Otmar'],
        17: ['Mahulena', 'Gertruda', 'Den boje za svobodu a demokracii'],
        18: ['Romana'],
        19: ['Alžběta'],
        20: ['Nikola', 'Nikol', 'Nikolas'],
        21: ['Albert'],
        22: ['Cecílie'],
        23: ['Klement'],
        24: ['Emílie'],
        25: ['Kateřina'],
        26: ['Artur'],
        27: ['Xenie', 'Oxana'],
        28: ['René'],
        29: ['Zina'],
        30: ['Ondřej'],
        31: [null]
    },
    12: {
        1: ['Iva'],
        2: ['Blanka'],
        3: ['Svatoslav', 'Svatoslava'],
        4: ['Barbora', 'Barbara'],
        5: ['Jitka'],
        6: ['Mikuláš', 'Nikolas'],
        7: ['Ambrož', 'Benjamín'],
        8: ['Květoslava'],
        9: ['Vratislav', 'Vratislava'],
        10: ['Julie'],
        11: ['Dana', 'Danuše'],
        12: ['Simona'],
        13: ['Lucie'],
        14: ['Lýdie'],
        15: ['Radana', 'Radan'],
        16: ['Albína'],
        17: ['Daniel'],
        18: ['Miloslav'],
        19: ['Ester'],
        20: ['Dagmar', 'Dáša'],
        21: ['Natálie'],
        22: ['Šimon'],
        23: ['Vlasta'],
        24: ['Adam a Eva', 'Štědrý den'],
        25: ['Boží hod vánoční', '1.svátek vánoční'],
        26: ['Štěpán', '2.svátek vánoční'],
        27: ['Žaneta', 'Melánie'],
        28: ['Bohumila'],
        29: ['Judita'],
        30: ['David'],
        31: ['Silvestr']
    },
} 

/**
 * 
 * 
 * @param {*} date 
 * @returns 
 */
module.exports.get = function (date) {
    const params = dateModule.getDayMonth(date);
    const day = params.day;
    const month = params.month;
    
    return nameDays[month][day]
};